title:              MoonJaeHoon's blog
email:              jh951229@naver.com
description:        Development & Studying
author:             MoonJaeHoon
baseurl:            "/"
url:                "https://MoonJaeHoon.github.io"

# Social Profiles
twitter_username:   
github_username:    MoonJaeHoon
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jemoji
